import os
import textwrap
import base64
import requests
from PIL import Image, ImageDraw, ImageFont

def generate_mermaid_diagram(mermaid_code: str, output_path: str = "daily_concept.png"):
    """
    Converts Mermaid code to an image using mermaid.ink and saves it.
    """
    # 1. Sanitize Mermaid Code (Ensure newline after declaration)
    # Common issue: "graph TD A-->B" fails. Needs "graph TD\nA-->B"
    import re
    # Pattern to find "graph TD" (or LR, etc) at the start, followed by anything that isn't a newline
    # We want to insert a newline after the direction.
    match = re.match(r"^\s*(graph\s+[A-Za-z]+)\s+(.*)", mermaid_code, re.DOTALL)
    if match:
        declaration = match.group(1)
        rest = match.group(2).strip()
        # Remove potential leading semicolon (common LLM artifact)
        if rest.startswith(";"):
            rest = rest[1:].strip()
            
        if not rest.startswith("\n"):
             mermaid_code = f"{declaration}\n{rest}"

    # Encode mermaid code to base64
    graph_bytes = mermaid_code.encode("utf8")
    base64_bytes = base64.b64encode(graph_bytes)
    base64_string = base64_bytes.decode("ascii")
    
    # 2. Build URL (using dark theme by default if possible, or just default)
    # mermaid.ink format: https://mermaid.ink/img/<base64>
    # To style it better, we might wrap it in a directive, but simple graph is fine.
    url = f"https://mermaid.ink/img/{base64_string}?bgColor=1a1a1a"
    
    try:
        response = requests.get(url)
        if response.status_code == 200:
            with open(output_path, 'wb') as f:
                f.write(response.content)
            return output_path
        else:
            print(f"Error fetching mermaid diagram: {response.status_code}")
            return None
    except Exception as e:
        print(f"Exception fetching mermaid diagram: {e}")
        return None

def generate_infographic(title: str, content: str, output_path: str = "infographic.png"):
    """
    Generates a simple, clean infographic card for an AI concept.
    (Legacy function kept for fallback or if user switches back)
    """
    # Configuration
    WIDTH, HEIGHT = 1080, 1080
    BG_COLOR = "#1a1a1a"   # Dark Gray/Black
    TEXT_COLOR = "#ffffff" # White
    ACCENT_COLOR = "#00d4ff" # Cyan/Blue
    
    # Create Image
    img = Image.new('RGB', (WIDTH, HEIGHT), color=BG_COLOR)
    draw = ImageDraw.Draw(img)
    
    # Load Fonts (Try to find a nice sans-serif, fallback to default)
    try:
        # Mac OS common font location
        title_font = ImageFont.truetype("/System/Library/Fonts/HelveticaNeue.ttc", 80, index=1) # Boldish
        content_font = ImageFont.truetype("/System/Library/Fonts/HelveticaNeue.ttc", 50)
        footer_font = ImageFont.truetype("/System/Library/Fonts/HelveticaNeue.ttc", 30)
    except IOError:
        try:
             # Linux/Ubuntu common
            title_font = ImageFont.truetype("DejaVuSans-Bold.ttf", 80)
            content_font = ImageFont.truetype("DejaVuSans.ttf", 50)
            footer_font = ImageFont.truetype("DejaVuSans.ttf", 30)
        except IOError:
            # Fallback
            title_font = ImageFont.load_default()
            content_font = ImageFont.load_default()
            footer_font = ImageFont.load_default()

    # Layout Calculations
    margin = 80
    max_width = WIDTH - (2 * margin)
    
    # Draw Title (Wrapped)
    # Note: simple textwrap might not be perfect for variable width fonts but good enough for this
    wrapped_title = textwrap.fill(title, width=20) # Approx char width for title
    
    # Draw "DAILY AI CONCEPT" Header
    draw.text((margin, 80), "DAILY AI CONCEPT", fill=ACCENT_COLOR, font=footer_font)
    
    # Draw Title
    current_h = 160
    draw.text((margin, current_h), wrapped_title, fill=TEXT_COLOR, font=title_font)
    
    # Calculate height of title to position content
    bbox = draw.textbbox((margin, current_h), wrapped_title, font=title_font)
    title_height = bbox[3] - bbox[1]
    current_h += title_height + 80 # Add spacing
    
    # Draw decorative line
    draw.line([(margin, current_h - 40), (WIDTH - margin, current_h - 40)], fill=ACCENT_COLOR, width=4)

    # Draw Content
    wrapped_content = textwrap.fill(content, width=35) # Approx char width for content
    draw.text((margin, current_h), wrapped_content, fill=TEXT_COLOR, font=content_font)
    
    # Draw Footer
    footer_text = "Generated by Gemini • Automated Agent"
    bbox_footer = draw.textbbox((0, 0), footer_text, font=footer_font)
    footer_w = bbox_footer[2] - bbox_footer[0]
    draw.text(((WIDTH - footer_w) / 2, HEIGHT - 100), footer_text, fill="#888888", font=footer_font)
    
    # Save
    img.save(output_path)
    return output_path

if __name__ == "__main__":
    generate_infographic("Retrieval Augmented Generation (RAG)", 
                         "RAG combines the power of LLMs with external data. Instead of relying just on training data, it looks up relevant info in a database and adds it to the prompt. This reduces hallucinations and keeps knowledge up-to-date.",
                         "test_infographic.png")
